lecture3/lecture3-project/hello/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("brian", views.brian, name="brian"),
]

lecture3/lecture3-project/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls")),
]

lecture3/lecture3-project/newyear/urls.py
from django.urls import path

from . import views

app_name = "newyear"
urlpatterns = [
    path("", views.index, name="index")
]

lecture3/lecture3-project/tasks/urls.py
from django.urls import path

from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add")
]

lecture3/lecture3-project/hello/models.py
from django.db import models

# Create your models here.

lecture3/lecture3-project/newyear/models.py
from django.db import models

# Create your models here.

lecture3/lecture3-project/tasks/models.py
from django.db import models

# Create your models here.

lecture3/lecture3-project/hello/views.py
from django.http import HttpResponse 
from django.shortcuts import render

# Create your views here.
def index(request):
  return render(request, "hello/index.html")

def brian(request):
  return HttpResponse("Hello, Brian!")

def greet(request, name):
  return render(request, "hello/greet.html", {
    "name": name.capitalize()
  })

lecture3/lecture3-project/newyear/views.py
from django.shortcuts import render
from datetime import datetime

# Create your views here.
def index(request):
  now = datetime.now()
  return render(request, "newyear/index.html", {
    "newyear": now.month == 1 and now.day == 1
  })

lecture3/lecture3-project/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

class NewTaskForm(forms.Form):
  task = forms.CharField(label="New Task")
  # priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
  if "tasks" not in request.session:
    request.session["tasks"] = []

  return render(request, "tasks/index.html", {
    "tasks": request.session["tasks"]
  })

def add(request):
  if request.method == "POST":
    form = NewTaskForm(request.POST)
    if form.is_valid():
      task = form.cleaned_data["task"]
      request.session["tasks"] += [task]
      return HttpResponseRedirect(reverse("tasks:index"))
    else:
      return render(request, "tasks/add.html", {
        "form": form
      })

  return render(request, "tasks/add.html", {
    "form": NewTaskForm()
  })

lecture3/lecture3-project/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello</title>
</head>
<body>
  <h1>Hello, {{ name }}!</h1>
</body>
</html>

lecture3/lecture3-project/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello!</title>
</head>
<body>
  <h1>Hello, world!</h1>
</body>
</html>

lecture3/lecture3-project/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Is It New Year's Day?</title>
  <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
  {% if newyear %}
    <h1>YES</h1>
  {% else %}
    <h1>NO</h1>
  {% endif %}
</body>
</html>

lecture3/lecture3-project/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
  <h1>Add Task</h1>
  <form action="{% url 'tasks:add' %}" method="POST">
    {% csrf_token %}
    <!-- <input type="text" name="task"> -->
    {{ form }}
    <input type="submit">
  </form>
  <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

lecture3/lecture3-project/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
  <h1>Tasks</h1>
  <ul>
  {% for task in tasks %}
    <li>{{ task }}</li>
  {% empty %}
    <li>No tasks.</li>
  {% endfor %}
  </ul>
  <a href="{% url 'tasks:add' %}">Add a New Task</a>
{% endblock %}

lecture3/lecture3-project/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tasks</title>
</head>
<body>
  {% block body %}
  {% endblock %}
</body>
</html>